### ISSUE TITLE
Sending e-mail user

### ISSUE THREAD

**Issue by majkelx** [araucaria-project/halina#19]
In the config there is:
```
FROM_EMAIL=noreply.araucaria
```
This is the sending user for SMTP credensials or value for email FROM header?

Usually there are different settings for both, e.g. DJANGO:
```
EMAIL_FROM_USER = "Grzegorz Brzęczyszczykiewicz"
EMAIL_HOST_USER = 'gbrz@superorg.com'
```

I suppose it's the user, but would be nice to have both, ang have it documented and named in the non-confusing way

**Comment by ernestworkspace** [comment]
Was changed in version 0.1.9

**Comment by majkelx** [comment]
sorry for being annoying, but now, if you have two options:

- `FROM_EMAIL`
- `FROM_EMAIL_USER`

then without documentation I would think that `FROM_EMAIL` is a FROM field of e-mail, and `FROM_EMAIL_USER` is an user pat of SMTP credentials, which is contrary to what is described.

I would propose following naming:

```
NATS_HOST=localhost
NATS_PORT=4222
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=noreply.araucaria           # valid SMTP login
SMTP_PASSWORD=your_email_password         # and corresponding password
# SMTP_USE_TLS=true     # if supported
# SMTP_USE_SSL=false    # if supported
FROM_NAME="Halina from OCM"  # Diplay name of FROM field
FROM_EMAIL=noreply.araucaria@camk.edu.pl  # valid e-mail
EMAILS_TO=["recipient1@example.com", "recipient2@example.com"]
SEND_AT=14
```

`FROM_NAME ` and `FROM_EMAIL` can be combined to sth like `EMAIL_FROM="Halina from OCM<noreply.araucaria@camk.edu.pl>" but then problems with character escaping are more likely.

**Comment by ernestworkspace** [comment]
Was changed in version 0.1.10
