### ISSUE TITLE
TELESCOPES_NAME

### ISSUE THREAD

**Issue by majkelx** [araucaria-project/halina#20]
```bash
poweruser@halina:~/src/halina$ TELESCOPES_NAME=["jk15","zb08"] poetry run services
2024-07-29 12:23:49 [WARNING] [main] Can not cast arg: TELESCOPES_NAME
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/poweruser/src/halina/src/halina/main.py", line 75, in main
    read_configuration(**kwargs)
  File "/home/poweruser/src/halina/src/halina/main.py", line 41, in read_configuration
    set_single_setting(GlobalConfig.TELESCOPES_NAME, kwargs, False)
  File "/home/poweruser/src/halina/src/halina/main.py", line 35, in set_single_setting
    GlobalConfig.set(name, setting)
  File "/home/poweruser/src/halina/src/configuration.py", line 81, in set
    cls.__conf.get(name).set_val(value)
  File "/home/poweruser/src/halina/src/configuration.py", line 38, in set_val
    raise TypeError(f"a parameter of type {type(v)} was received and a parameter of type  "
TypeError: a parameter of type <class 'str'> was received and a parameter of type  <class 'list'> was expected
```

Looks like there is a problem with parsing list

Additionally:
- The casting error (may be common) can be handled nicer (recognized and logged, without stacktrace)
- The option `TELESCOPES_NAME` should be rather spelled `TELESCOPE_NAMES`

**Comment by ernestworkspace** [comment]
This error is due to aggressive validation before launch services. This error is caused by missing '' symbol. If we pass an env-variable in the console it has to be wrapped in '', however when importing .env it doesn't have to.

**Comment by ernestworkspace** [comment]
Problem is that env-variables defined in the console must be wrapped in a single `' '` . When defining variables in `.env` this is not required.

**Comment by majkelx** [comment]
The standard way, known to me, to use `.env` files to set variables for a single command is:
```bash
env $(cat .env | xargs) poetry run services
```
and I have exactly the same error. 

I have line i `.env`:
```.env
TELESCOPES_NAME=["wk06","zb08","jk15"]
```

If there is restricted way how to use `.env` for this project, add it to the doc or make it easier to define config.

**Comment by majkelx** [comment]
`env $(cat .env | xargs)`, as well as in first example, is going to define list without `" "`: `TELESCOPES_NAME=[wk06,zb08,jk15]`

But if that is madatory, I dont know how to use `.env` file from the example

**Comment by ernestworkspace** [comment]
I see, so maybe it would be better if we required `' '` everywhere?

**Comment by majkelx** [comment]
I see, that in envvars, lists are usually encoded like:
```
LISTVAR=item1,item2,item3
```

if there is a space in element then both
```
LISTVAR=item1,item2,"item 3"
LISTVAR2="item1,item2,item 3" 
```
should work also, (shell will eat `"` but keep the variable consistent).

This format is understood by pedantic config (and thus FastAPI), and also here is about django:

 https://tech.serhatteker.com/post/2021-10/django-environ-list/

**Comment by majkelx** [comment]
that way one can not distinguish between single value and one-element list by just looking at `.env` but people live with that.

**Comment by majkelx** [comment]
but ok, you wrote in the documentation "in json format", so it's correct, user have to ensure json format in the variable set.
Although it's not convinient to set env variables to json mainly because you may struggle with escape sequences for special characters.

**Comment by majkelx** [comment]
but anyway this makes using .env annoying (instead of simplest)

I do not know how you are using them with this json settings.

Chat-gpt, an ultimate expert ;) suggest me to write buash scipt like this just to prepare to run the software:

```bash
Skrypt run_with_env.sh
bash
Copy code
#!/bin/bash

# Load environment variables from .env file while preserving quotes
set -a
while IFS= read -r line; do
  if [[ ! $line =~ ^# && -n $line ]]; then
    IFS='=' read -r key value <<< "$line"
    export "$key=$value"
  fi
done < .env
set +a
```

**Comment by ernestworkspace** [comment]
I have improved the instructions and the stack trace logging. For now. I will look for another alternative to this JSON

**Comment by majkelx** [comment]
poza tym 
`FROM_NAME="Halina from OCM" ` i tak mi rozwala na kawałki i chce uruchamiać `from`. Trochę nie wiem jak sobie nawet ze spacjami poradzić ile bym ich nie escapował.

**Comment by ernestworkspace** [comment]
In version 0.1.11 change settings source to dynaconf. Check README.md. From now properties will be get from settings.toml or command arguments.
